#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: 'cloudcomputing'
  CLOUD_SQL_PASSWORD: 'cloudcomputing'
  CLOUD_SQL_DATABASE_NAME: 'cloudcomputingtask'
  CLOUD_SQL_CONNECTION_NAME: 'cloudcomputingcw-343618:europe-west2:cloudcomputingtasks'
