#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: <db_username>
  CLOUD_SQL_PASSWORD: <db_password>
  CLOUD_SQL_DATABASE_NAME: <db_name>
  CLOUD_SQL_CONNECTION_NAME: <connection_name>
